name: innosetup
description: Make windows installer for Flutter & vanilla Dart powered apps powered by Inno Setup.
version: 0.1.3

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ">=1.7.0"
  version: ^3.0.2
  process_run: ^0.13.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
